# @package _global_
dataset:
  _target_: src.data.M5DatasetCollection       # Will be dynamically instantiated
  seed: ${exp.seed}
  name: m5
  path: data\processed\sales.csv                # Path with MIMIC-3 dataset (HDFStore)
  min_seq_length: 31                                   # Min sequence length in cohort
  max_seq_length: 34                                   # Max sequence length in cohort
  max_number: 5000                                     # Maximum number of patients in cohort
  projection_horizon: 5                                # Range of tau-step-ahead prediction (tau = projection_horizon + 1)
  split:
    val: 0.15
    test: 0.15
  val_batch_size: 64                                  # Batch size for evaluation
  treatment_mode: multilabel
  autoregressive: True

  treatment_list:
    - sell_price
  outcome_list:
    - sales
  vital_list:
    - weekday
    - wday
    - month
    - year
    - snap_CA
    - snap_WI
    - snap_TX
    - Chanukah End
    - Christmas
    - Cinco De Mayo
    - ColumbusDay
    - Easter
    - Eid al-Fitr
    - EidAlAdha
    - Father's day
    - Halloween
    - IndependenceDay
    - LaborDay
    - LentStart
    - LentWeek2
    - MartinLutherKingDay
    - MemorialDay
    - Mother's day
    - NBAFinalsEnd
    - NBAFinalsStart
    - NewYear
    - OrthodoxChristmas
    - OrthodoxEaster
    - Pesach End
    - PresidentsDay
    - Purim End
    - Ramadan starts
    - StPatricksDay
    - SuperBowl
    - Thanksgiving
    - ValentinesDay
    - VeteransDay
    - Cultural
    - National
    - Religious
    - Sporting
    - price_change
  static_list:
    - item_id
    - dept_id
    - cat_id
    - store_id
    - state_id
  drop_first: False                                     # One-hot encoding of categorical static features

exp:
  unscale_rmse: True
  percentage_rmse: False

